/*
 nouislider - 11.1.0 - 2018-04-02 11:18:13 */
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(c,q,e){c!=Array.prototype&&c!=Object.prototype&&(c[q]=e.value)};$jscomp.getGlobal=function(c){return"undefined"!=typeof window&&window===c?c:"undefined"!=typeof global&&null!=global?global:c};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var c=0;return function(q){return $jscomp.SYMBOL_PREFIX+(q||"")+c++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var c=$jscomp.global.Symbol.iterator;c||(c=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[c]&&$jscomp.defineProperty(Array.prototype,c,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(c){var q=0;return $jscomp.iteratorPrototype(function(){return q<c.length?{done:!1,value:c[q++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(c){$jscomp.initSymbolIterator();c={next:c};c[$jscomp.global.Symbol.iterator]=function(){return this};return c};$jscomp.iteratorFromArray=function(c,q){$jscomp.initSymbolIterator();c instanceof String&&(c+="");var e=0,g={next:function(){if(e<c.length){var t=e++;return{value:q(t,c[t]),done:!1}}g.next=function(){return{done:!0,value:void 0}};return g.next()}};g[Symbol.iterator]=function(){return g};return g};
$jscomp.polyfill=function(c,q,e,g){if(q){e=$jscomp.global;c=c.split(".");for(g=0;g<c.length-1;g++){var t=c[g];t in e||(e[t]={});e=e[t]}c=c[c.length-1];g=e[c];q=q(g);q!=g&&null!=q&&$jscomp.defineProperty(e,c,{configurable:!0,writable:!0,value:q})}};$jscomp.polyfill("Array.prototype.keys",function(c){return c?c:function(){return $jscomp.iteratorFromArray(this,function(c){return c})}},"es6","es3");
$jscomp.polyfill("Array.prototype.values",function(c){return c?c:function(){return $jscomp.iteratorFromArray(this,function(c,e){return e})}},"es8","es3");$jscomp.findInternal=function(c,q,e){c instanceof String&&(c=String(c));for(var g=c.length,t=0;t<g;t++){var A=c[t];if(q.call(e,A,t,c))return{i:t,v:A}}return{i:-1,v:void 0}};$jscomp.polyfill("Array.prototype.find",function(c){return c?c:function(c,e){return $jscomp.findInternal(this,c,e).v}},"es6","es3");
!function(c){"function"==typeof define&&define.amd?define([],c):"object"==typeof exports?module.exports=c():window.noUiSlider=c()}(function(){function c(b){return null!==b&&void 0!==b}function q(b){b.preventDefault()}function e(b){return b.filter(function(a){return!this[a]&&(this[a]=!0)},{})}function g(b){return"number"==typeof b&&!isNaN(b)&&isFinite(b)}function t(b,a,c){0<c&&(r(b,a),setTimeout(function(){C(b,a)},c))}function A(b){return Array.isArray(b)?b:[b]}function L(b){b=String(b);b=b.split(".");
return 1<b.length?b[1].length:0}function r(b,a){b.classList?b.classList.add(a):b.className+=" "+a}function C(b,a){b.classList?b.classList.remove(a):b.className=b.className.replace(new RegExp("(^|\\b)"+a.split(" ").join("|")+"(\\b|$)","gi")," ")}function pa(b){var a=void 0!==window.pageXOffset,c="CSS1Compat"===(b.compatMode||"");return{x:a?window.pageXOffset:c?b.documentElement.scrollLeft:b.body.scrollLeft,y:a?window.pageYOffset:c?b.documentElement.scrollTop:b.body.scrollTop}}function l(){var b=!1;
try{var a=Object.defineProperty({},"passive",{get:function(){b=!0}});window.addEventListener("test",null,a)}catch(F){}return b}function G(b,a){return 100*a/(b[1]-b[0])}function M(b,a){for(var c=1;b>=a[c];)c+=1;return c}function H(b,a,c){var F;if("number"==typeof a&&(a=[a]),!Array.isArray(a))throw Error("noUiSlider ("+m+"): 'range' contains invalid value.");if(F="min"===b?0:"max"===b?100:parseFloat(b),!g(F)||!g(a[0]))throw Error("noUiSlider ("+m+"): 'range' value isn't numeric.");c.xPct.push(F);c.xVal.push(a[0]);
F?c.xSteps.push(!isNaN(a[1])&&a[1]):isNaN(a[1])||(c.xSteps[0]=a[1]);c.xHighestCompleteStep.push(0)}function S(b,a,c){if(!a)return!0;c.xSteps[b]=G([c.xVal[b],c.xVal[b+1]],a)/(100/(c.xPct[b+1]-c.xPct[b]));a=Math.ceil(Number(((c.xVal[b+1]-c.xVal[b])/c.xNumSteps[b]).toFixed(3))-1);c.xHighestCompleteStep[b]=c.xVal[b]+c.xNumSteps[b]*a}function x(b,a,c){this.xPct=[];this.xVal=[];this.xSteps=[c||!1];this.xNumSteps=[!1];this.xHighestCompleteStep=[];this.snap=a;var k;a=[];for(k in b)b.hasOwnProperty(k)&&a.push([b[k],
k]);a.length&&"object"==typeof a[0][0]?a.sort(function(a,b){return a[0][0]-b[0][0]}):a.sort(function(a,b){return a[0]-b[0]});for(k=0;k<a.length;k++)H(a[k][1],a[k][0],this);this.xNumSteps=this.xSteps.slice(0);for(k=0;k<this.xNumSteps.length;k++)S(k,this.xNumSteps[k],this)}function T(b){if("object"==typeof b&&"function"==typeof b.to&&"function"==typeof b.from)return!0;throw Error("noUiSlider ("+m+"): 'format' requires 'to' and 'from' methods.");}function N(b,a){if(!g(a))throw Error("noUiSlider ("+m+
"): 'step' is not numeric.");b.singleStep=a}function ca(b,a){if("object"!=typeof a||Array.isArray(a))throw Error("noUiSlider ("+m+"): 'range' is not an object.");if(void 0===a.min||void 0===a.max)throw Error("noUiSlider ("+m+"): Missing 'min' or 'max' in 'range'.");if(a.min===a.max)throw Error("noUiSlider ("+m+"): 'range' 'min' and 'max' cannot be equal.");b.spectrum=new x(a,b.snap,b.singleStep)}function da(b,a){if(a=A(a),!Array.isArray(a)||!a.length)throw Error("noUiSlider ("+m+"): 'start' option is incorrect.");
b.handles=a.length;b.start=a}function ea(b,a){if(b.snap=a,"boolean"!=typeof a)throw Error("noUiSlider ("+m+"): 'snap' option must be a boolean.");}function fa(b,a){if(b.animate=a,"boolean"!=typeof a)throw Error("noUiSlider ("+m+"): 'animate' option must be a boolean.");}function ha(b,a){if(b.animationDuration=a,"number"!=typeof a)throw Error("noUiSlider ("+m+"): 'animationDuration' option must be a number.");}function va(b,a){var c,k=[!1];if("lower"===a?a=[!0,!1]:"upper"===a&&(a=[!1,!0]),!0===a||
!1===a){for(c=1;c<b.handles;c++)k.push(a);k.push(!1)}else{if(!Array.isArray(a)||!a.length||a.length!==b.handles+1)throw Error("noUiSlider ("+m+"): 'connect' option doesn't match handle count.");k=a}b.connect=k}function wa(b,a){switch(a){case "horizontal":b.ort=0;break;case "vertical":b.ort=1;break;default:throw Error("noUiSlider ("+m+"): 'orientation' option is invalid.");}}function U(b,a){if(!g(a))throw Error("noUiSlider ("+m+"): 'margin' option must be numeric.");if(0!==a&&(b.margin=b.spectrum.getMargin(a),
!b.margin))throw Error("noUiSlider ("+m+"): 'margin' option is only supported on linear sliders.");}function xa(b,a){if(!g(a))throw Error("noUiSlider ("+m+"): 'limit' option must be numeric.");if(b.limit=b.spectrum.getMargin(a),!b.limit||2>b.handles)throw Error("noUiSlider ("+m+"): 'limit' option is only supported on linear sliders with 2 or more handles.");}function ya(b,a){if(!g(a)&&!Array.isArray(a))throw Error("noUiSlider ("+m+"): 'padding' option must be numeric or array of exactly 2 numbers.");
if(Array.isArray(a)&&2!==a.length&&!g(a[0])&&!g(a[1]))throw Error("noUiSlider ("+m+"): 'padding' option must be numeric or array of exactly 2 numbers.");if(0!==a){if(Array.isArray(a)||(a=[a,a]),b.padding=[b.spectrum.getMargin(a[0]),b.spectrum.getMargin(a[1])],!1===b.padding[0]||!1===b.padding[1])throw Error("noUiSlider ("+m+"): 'padding' option is only supported on linear sliders.");if(0>b.padding[0]||0>b.padding[1])throw Error("noUiSlider ("+m+"): 'padding' option must be a positive number(s).");
if(100<=b.padding[0]+b.padding[1])throw Error("noUiSlider ("+m+"): 'padding' option must not exceed 100% of the range.");}}function za(b,a){switch(a){case "ltr":b.dir=0;break;case "rtl":b.dir=1;break;default:throw Error("noUiSlider ("+m+"): 'direction' option was not recognized.");}}function Aa(b,a){if("string"!=typeof a)throw Error("noUiSlider ("+m+"): 'behaviour' must be a string containing options.");var c=0<=a.indexOf("tap"),k=0<=a.indexOf("drag"),e=0<=a.indexOf("fixed"),l=0<=a.indexOf("snap");
a=0<=a.indexOf("hover");if(e){if(2!==b.handles)throw Error("noUiSlider ("+m+"): 'fixed' behaviour must be used with 2 handles");U(b,b.start[1]-b.start[0])}b.events={tap:c||l,drag:k,fixed:e,snap:l,hover:a}}function Ba(b,a){if(!1!==a)if(!0===a)for(b.tooltips=[],a=0;a<b.handles;a++)b.tooltips.push(!0);else{if(b.tooltips=A(a),b.tooltips.length!==b.handles)throw Error("noUiSlider ("+m+"): must pass a formatter for all handles.");b.tooltips.forEach(function(a){if("boolean"!=typeof a&&("object"!=typeof a||
"function"!=typeof a.to))throw Error("noUiSlider ("+m+"): 'tooltips' must be passed a formatter or 'false'.");})}}function Ca(b,a){b.ariaFormat=a;T(a)}function Da(b,a){b.format=a;T(a)}function Ea(b,a){if("string"!=typeof a&&!1!==a)throw Error("noUiSlider ("+m+"): 'cssPrefix' must be a string or `false`.");b.cssPrefix=a}function Fa(b,a){if("object"!=typeof a)throw Error("noUiSlider ("+m+"): 'cssClasses' must be an object.");if("string"==typeof b.cssPrefix){b.cssClasses={};for(var c in a)a.hasOwnProperty(c)&&
(b.cssClasses[c]=b.cssPrefix+a[c])}else b.cssClasses=a}function qa(b){var a={margin:0,limit:0,padding:0,animate:!0,animationDuration:300,ariaFormat:V,format:V},e={step:{r:!1,t:N},start:{r:!0,t:da},connect:{r:!0,t:va},direction:{r:!0,t:za},snap:{r:!1,t:ea},animate:{r:!1,t:fa},animationDuration:{r:!1,t:ha},range:{r:!0,t:ca},orientation:{r:!1,t:wa},margin:{r:!1,t:U},limit:{r:!1,t:xa},padding:{r:!1,t:ya},behaviour:{r:!0,t:Aa},ariaFormat:{r:!1,t:Ca},format:{r:!1,t:Da},tooltips:{r:!1,t:Ba},cssPrefix:{r:!0,
t:Ea},cssClasses:{r:!0,t:Fa}},k={connect:!1,direction:"ltr",behaviour:"tap",orientation:"horizontal",cssPrefix:"noUi-",cssClasses:{target:"target",base:"base",origin:"origin",handle:"handle",handleLower:"handle-lower",handleUpper:"handle-upper",horizontal:"horizontal",vertical:"vertical",background:"background",connect:"connect",connects:"connects",ltr:"ltr",rtl:"rtl",draggable:"draggable",drag:"state-drag",tap:"state-tap",active:"active",tooltip:"tooltip",pips:"pips",pipsHorizontal:"pips-horizontal",
pipsVertical:"pips-vertical",marker:"marker",markerHorizontal:"marker-horizontal",markerVertical:"marker-vertical",markerNormal:"marker-normal",markerLarge:"marker-large",markerSub:"marker-sub",value:"value",valueHorizontal:"value-horizontal",valueVertical:"value-vertical",valueNormal:"value-normal",valueLarge:"value-large",valueSub:"value-sub"}};b.format&&!b.ariaFormat&&(b.ariaFormat=b.format);Object.keys(e).forEach(function(l){if(!c(b[l])&&void 0===k[l]){if(e[l].r)throw Error("noUiSlider ("+m+"): '"+
l+"' is required.");return!0}e[l].t(a,c(b[l])?b[l]:k[l])});a.pips=b.pips;var l=document.createElement("div"),g=void 0!==l.style.msTransform;a.transformRule=void 0!==l.style.transform?"transform":g?"msTransform":"webkitTransform";return a.style=[["left","top"],["right","bottom"]][a.dir][a.ort],a}function Ga(b,a,c){function k(a,b){var d=O.createElement("div");return b&&r(d,b),a.appendChild(d),d}function g(b,f){b=k(b,a.cssClasses.origin);var d=k(b,a.cssClasses.handle);return d.setAttribute("data-handle",
f),d.setAttribute("tabindex","0"),d.setAttribute("role","slider"),d.setAttribute("aria-orientation",a.ort?"vertical":"horizontal"),0===f?r(d,a.cssClasses.handleLower):f===a.handles-1&&r(d,a.cssClasses.handleUpper),b}function G(b,f){return!!a.tooltips[f]&&k(b.firstChild,a.cssClasses.tooltip)}function F(){var b=u.map(G);ia("update",function(d,h,c){b[h]&&(d=d[h],!0!==a.tooltips[h]&&(d=a.tooltips[h].to(c[h])),b[h].innerHTML=d)})}function x(a,b,h){if("range"===a||"steps"===a)return v.xVal;if("count"===
a){if(2>b)throw Error("noUiSlider ("+m+"): 'values' (>= 2) required for mode 'count'.");a=b-1;var d=100/a;for(b=[];a--;)b[a]=a*d;b.push(100);a="positions"}return"positions"===a?b.map(function(a){return v.fromStepping(h?v.getStep(a):a)}):"values"===a?h?b.map(function(a){return v.fromStepping(v.getStep(v.toStepping(a)))}):b:void 0}function M(a,b,h){var d={},f=v.xVal[0],c=v.xVal[v.xVal.length-1],k=!1,l=!1,m=0;return h=e(h.slice().sort(function(a,b){return a-b})),h[0]!==f&&(h.unshift(f),k=!0),h[h.length-
1]!==c&&(h.push(c),l=!0),h.forEach(function(f,c){var n,p=h[c+1];if("steps"===b&&(n=v.xNumSteps[c]),n||(n=p-f),!1!==f&&void 0!==p)for(n=Math.max(n,1E-7);f<=p;f=(f+n).toFixed(7)/1){var ja=v.toStepping(f);var e=ja-m;var I=e/a;I=Math.round(I);var g=e/I;for(e=1;e<=I;e+=1){var G=m+e*g;d[G.toFixed(5)]=["x",0]}I=-1<h.indexOf(f)?1:"steps"===b?2:0;!c&&k&&(I=0);f===p&&l||(d[ja.toFixed(5)]=[f,I]);m=ja}}),d}function T(b,f,h){function d(b,d){var f=d===a.cssClasses.value;return d+" "+(f?m:g)[a.ort]+" "+(f?e:l)[b]}
var c=O.createElement("div"),e=[a.cssClasses.valueNormal,a.cssClasses.valueLarge,a.cssClasses.valueSub],l=[a.cssClasses.markerNormal,a.cssClasses.markerLarge,a.cssClasses.markerSub],m=[a.cssClasses.valueHorizontal,a.cssClasses.valueVertical],g=[a.cssClasses.markerHorizontal,a.cssClasses.markerVertical];return r(c,a.cssClasses.pips),r(c,0===a.ort?a.cssClasses.pipsHorizontal:a.cssClasses.pipsVertical),Object.keys(b).forEach(function(n){var p=b[n];p[1]=p[1]&&f?f(p[0],p[1]):p[1];var e=k(c,!1);e.className=
d(p[1],a.cssClasses.marker);e.style[a.style]=n+"%";p[1]&&(e=k(c,!1),e.className=d(p[1],a.cssClasses.value),e.setAttribute("data-value",p[0]),e.style[a.style]=n+"%",e.innerText=h.to(p[0]))}),c}function H(){Q&&(Q.parentElement.removeChild(Q),Q=null)}function N(a){H();var b=a.mode,d=a.density||1,c=a.filter||!1,p=x(b,a.values||!1,a.stepped||!1);b=M(d,b,p);return Q=y.appendChild(T(b,c,a.format||{to:Math.round}))}function S(){var b=D.getBoundingClientRect(),f="offset"+["Width","Height"][a.ort];return 0===
a.ort?b.width||D[f]:b.height||D[f]}function J(b,f,h,c){var d=function(d){var n;if(n=!!(d=da(d,c.pageOffset,c.target||f)))if(n=!(y.hasAttribute("disabled")&&!c.doNotReject)){n=y;var p=a.cssClasses.tap;n=!((n.classList?n.classList.contains(p):(new RegExp("\\b"+p+"\\b")).test(n.className))&&!c.doNotReject)&&!(b===K.start&&void 0!==d.buttons&&1<d.buttons)&&(!c.hover||!d.buttons)&&(ra||d.preventDefault(),d.calcPoint=d.points[a.ort],void h(d,c))}return n},n=[];return b.split(" ").forEach(function(a){f.addEventListener(a,
d,!!ra&&{passive:!0});n.push([a,d])}),n}function da(a,b,h){var d=0===a.type.indexOf("touch"),f=0===a.type.indexOf("mouse"),c=0===a.type.indexOf("pointer");if(0===a.type.indexOf("MSPointer")&&(c=!0),d){var e=function(a){return a.target===h||h.contains(a.target)};if("touchstart"===a.type){var k=Array.prototype.filter.call(a.touches,e);if(1<k.length)return!1;e=k[0].pageX;k=k[0].pageY}else{k=Array.prototype.find.call(a.changedTouches,e);if(!k)return!1;e=k.pageX;k=k.pageY}}return b=b||pa(O),(f||c)&&(e=
a.clientX+b.x,k=a.clientY+b.y),a.pageOffset=b,a.points=[e,k],a.cursor=f||c,a}function L(b){var d=D;var c=a.ort;var n=d.getBoundingClientRect(),p=d.ownerDocument;d=p.documentElement;p=pa(p);c=(/webkit.*Chrome.*Mobile/i.test(navigator.userAgent)&&(p.x=0),c?n.top+p.y-d.clientTop:n.left+p.x-d.clientLeft);b=100*(b-c)/S();return b=Math.max(Math.min(b,100),0),a.dir?100-b:b}function ca(a){var b=100,d=!1;return u.forEach(function(c,f){c.hasAttribute("disabled")||(c=Math.abs(w[f]-a),(c<b||100===c&&100===b)&&
(d=f,b=c))}),d}function U(a,b){"mouseout"===a.type&&"HTML"===a.target.nodeName&&null===a.relatedTarget&&ka(a,b)}function V(b,c){if(-1===navigator.appVersion.indexOf("MSIE 9")&&0===b.buttons&&0!==c.buttonsProperty)return ka(b,c);b=(a.dir?-1:1)*(b.calcPoint-c.startCalcPoint);sa(0<b,100*b/c.baseSize,c.locations,c.handleNumbers)}function ka(b,c){c.handle&&(C(c.handle,a.cssClasses.active),--la);c.listeners.forEach(function(a){W.removeEventListener(a[0],a[1])});0===la&&(C(y,a.cssClasses.drag),ma(),b.cursor&&
(X.style.cursor="",X.removeEventListener("selectstart",q)));c.handleNumbers.forEach(function(a){z("change",a);z("set",a);z("end",a)})}function na(b,c){if(1===c.handleNumbers.length){var d=u[c.handleNumbers[0]];if(d.hasAttribute("disabled"))return!1;var f=d.children[0];la+=1;r(f,a.cssClasses.active)}b.stopPropagation();d=[];var p=J(K.move,W,V,{target:b.target,handle:f,listeners:d,startCalcPoint:b.calcPoint,baseSize:S(),pageOffset:b.pageOffset,handleNumbers:c.handleNumbers,buttonsProperty:b.buttons,
locations:w.slice()}),e=J(K.end,W,ka,{target:b.target,handle:f,listeners:d,doNotReject:!0,handleNumbers:c.handleNumbers});f=J("mouseout",W,U,{target:b.target,handle:f,listeners:d,doNotReject:!0,handleNumbers:c.handleNumbers});d.push.apply(d,p.concat(e,f));b.cursor&&(X.style.cursor=getComputedStyle(b.target).cursor,1<u.length&&r(y,a.cssClasses.drag),X.addEventListener("selectstart",q,!1));c.handleNumbers.forEach(function(a){z("start",a)})}function ea(b){b.stopPropagation();var c=L(b.calcPoint),d=ca(c);
if(!1===d)return!1;a.events.snap||t(y,a.cssClasses.tap,a.animationDuration);Y(d,c,!0,!0);ma();z("slide",d,!0);z("update",d,!0);z("change",d,!0);z("set",d,!0);a.events.snap&&na(b,{handleNumbers:[d]})}function fa(a){a=L(a.calcPoint);a=v.getStep(a);var b=v.fromStepping(a);Object.keys(B).forEach(function(a){"hover"===a.split(".")[0]&&B[a].forEach(function(a){a.call(Z,b)})})}function ia(a,b){B[a]=B[a]||[];B[a].push(b);"update"===a.split(".")[0]&&u.forEach(function(a,b){z("update",b)})}function z(b,c,h){Object.keys(B).forEach(function(d){var f=
d.split(".")[0];b===f&&B[d].forEach(function(b){b.call(Z,R.map(a.format.to),c,R.slice(),h||!1,w.slice())})})}function aa(b,c,h,n,e,k){return 1<u.length&&(n&&0<c&&(h=Math.max(h,b[c-1]+a.margin)),e&&c<u.length-1&&(h=Math.min(h,b[c+1]-a.margin))),1<u.length&&a.limit&&(n&&0<c&&(h=Math.min(h,b[c-1]+a.limit)),e&&c<u.length-1&&(h=Math.max(h,b[c+1]-a.limit))),a.padding&&(0===c&&(h=Math.max(h,a.padding[0])),c===u.length-1&&(h=Math.min(h,100-a.padding[1]))),h=v.getStep(h),!((h=Math.max(Math.min(h,100),0))===
b[c]&&!k)&&h}function oa(b,c){var d=a.ort;return(d?c:b)+", "+(d?b:c)}function sa(a,b,c,n){var d=c.slice(),h=[!a,a],f=[a,!a];n=n.slice();a&&n.reverse();1<n.length?n.forEach(function(a,c){c=aa(d,a,d[a]+b,h[c],f[c],!1);!1===c?b=0:(b=c-d[a],d[a]=c)}):h=f=[!0];var e=!1;n.forEach(function(a,d){e=Y(a,c[a]+b,h[d],f[d])||e});e&&n.forEach(function(a){z("update",a);z("slide",a)})}function ma(){P.forEach(function(a){u[a].style.zIndex=3+(u.length+(50<w[a]?-1:1)*a)})}function Y(b,c,h,e){if(h=!1!==(c=aa(w,b,c,h,
e,!1)))w[b]=c,R[b]=v.fromStepping(c),c="translate("+oa((a.dir?100-c:c)-ha+"%","0")+")",u[b].style[a.transformRule]=c,ta(b),ta(b+1),h=!0;return h}function ta(b){if(E[b]){var c=0,d=100;0!==b&&(c=w[b-1]);b!==E.length-1&&(d=w[b]);d-=c;c="translate("+oa((a.dir?100-c-d:c)+"%","0")+")";d="scale("+oa(d/100,"1")+")";E[b].style[a.transformRule]=c+" "+d}}function ba(b,c){var d=A(b);b=void 0===w[0];c=void 0===c||!!c;a.animate&&!b&&t(y,a.cssClasses.tap,a.animationDuration);P.forEach(function(b){var c=d[b];var h=
null===c||!1===c||void 0===c?w[b]:("number"==typeof c&&(c=String(c)),c=a.format.from(c),c=v.toStepping(c),!1===c||isNaN(c)?w[b]:c);Y(b,h,!0,!1)});P.forEach(function(a){Y(a,w[a],!0,!0)});ma();P.forEach(function(a){z("update",a);null!==d[a]&&c&&z("set",a)})}function ua(){var b=R.map(a.format.to);return 1===b.length?b[0]:b}var D,u,E,Z,Q,K=window.navigator.pointerEnabled?{start:"pointerdown",move:"pointermove",end:"pointerup"}:window.navigator.msPointerEnabled?{start:"MSPointerDown",move:"MSPointerMove",
end:"MSPointerUp"}:{start:"mousedown touchstart",move:"mousemove touchmove",end:"mouseup touchend"},ra=window.CSS&&CSS.supports&&CSS.supports("touch-action","none")&&l(),y=b,w=[],P=[],la=0,v=a.spectrum,R=[],B={},O=b.ownerDocument,W=O.documentElement,X=O.body,ha="rtl"===O.dir||1===a.ort?0:100;return function(b){r(b,a.cssClasses.target);0===a.dir?r(b,a.cssClasses.ltr):r(b,a.cssClasses.rtl);0===a.ort?r(b,a.cssClasses.horizontal):r(b,a.cssClasses.vertical);D=k(b,a.cssClasses.base)}(y),function(b,c){var d=
k(c,a.cssClasses.connects);u=[];E=[];E.push(!!b[0]&&k(d,a.cssClasses.connect));for(var f=0;f<a.handles;f++)u.push(g(c,f)),P[f]=f,E.push(!!b[f+1]&&k(d,a.cssClasses.connect))}(a.connect,D),function(b){b.fixed||u.forEach(function(a,b){J(K.start,a.children[0],na,{handleNumbers:[b]})});b.tap&&J(K.start,D,ea,{});b.hover&&J(K.move,D,fa,{hover:!0});b.drag&&E.forEach(function(c,d){if(!1!==c&&0!==d&&d!==E.length-1){var h=u[d-1],f=u[d],e=[c];r(c,a.cssClasses.draggable);b.fixed&&(e.push(h.children[0]),e.push(f.children[0]));
e.forEach(function(a){J(K.start,a,na,{handles:[h,f],handleNumbers:[d-1,d]})})}})}(a.events),ba(a.start),Z={destroy:function(){for(var b in a.cssClasses)a.cssClasses.hasOwnProperty(b)&&C(y,a.cssClasses[b]);for(;y.firstChild;)y.removeChild(y.firstChild);delete y.noUiSlider},steps:function(){return w.map(function(a,b){var c=v.getNearbySteps(a),d=R[b];b=c.thisStep.step;!1!==b&&d+b>c.stepAfter.startValue&&(b=c.stepAfter.startValue-d);c=d>c.thisStep.startValue?c.thisStep.step:!1!==c.stepBefore.step&&d-
c.stepBefore.highestStep;100===a?b=null:0===a&&(c=null);a=v.countStepDecimals();return null!==b&&!1!==b&&(b=Number(b.toFixed(a))),null!==c&&!1!==c&&(c=Number(c.toFixed(a))),[c,b]})},on:ia,off:function(a){var b=a&&a.split(".")[0],c=b&&a.substring(b.length);Object.keys(B).forEach(function(a){var d=a.split(".")[0],e=a.substring(d.length);b&&b!==d||c&&c!==e||delete B[a]})},get:ua,set:ba,reset:function(b){ba(a.start,b)},__moveHandles:function(a,b,c){sa(a,b,w,c)},options:c,updateOptions:function(b,e){var d=
ua(),k="margin limit padding range animate snap step format".split(" ");k.forEach(function(a){void 0!==b[a]&&(c[a]=b[a])});var f=qa(c);k.forEach(function(c){void 0!==b[c]&&(a[c]=f[c])});v=f.spectrum;a.margin=f.margin;a.limit=f.limit;a.padding=f.padding;a.pips&&N(a.pips);w=[];ba(b.start||d,e)},target:y,removePips:H,pips:N},a.pips&&N(a.pips),a.tooltips&&F(),function(){ia("update",function(b,c,e,k,l){P.forEach(function(b){var c=u[b],d=aa(w,b,0,!0,!0,!0),k=aa(w,b,100,!0,!0,!0),f=l[b];b=a.ariaFormat.to(e[b]);
c.children[0].setAttribute("aria-valuemin",d.toFixed(1));c.children[0].setAttribute("aria-valuemax",k.toFixed(1));c.children[0].setAttribute("aria-valuenow",f.toFixed(1));c.children[0].setAttribute("aria-valuetext",b)})})}(),Z}var m="11.1.0";x.prototype.getMargin=function(b){var a=this.xNumSteps[0];if(a&&0!=b/a%1)throw Error("noUiSlider ("+m+"): 'limit', 'margin' and 'padding' must be divisible by step.");return 2===this.xPct.length&&G(this.xVal,b)};x.prototype.toStepping=function(b){var a=this.xVal,
c=this.xPct;if(b>=a.slice(-1)[0])var e=100;else{var l=M(b,a);e=c[l-1];c=c[l];a=[a[l-1],a[l]];b=G(a,0>a[0]?b+Math.abs(a[0]):b-a[0]);e+=b/(100/(c-e))}return e};x.prototype.fromStepping=function(b){var a=this.xVal,c=this.xPct;if(100<=b)b=a.slice(-1)[0];else{var e=M(b,c),l=c[e-1];a=[a[e-1],a[e]];b=100/(c[e]-l)*(b-l)*(a[1]-a[0])/100+a[0]}return b};x.prototype.getStep=function(b){var a=this.xPct,c=this.xSteps,e=this.snap;if(100!==b){var l=M(b,a),m=a[l-1],g=a[l];e?b=b-m>(g-m)/2?g:m:c[l-1]&&(c=c[l-1],b=a[l-
1]+Math.round((b-a[l-1])/c)*c)}return b};x.prototype.getNearbySteps=function(b){b=M(b,this.xPct);return{stepBefore:{startValue:this.xVal[b-2],step:this.xNumSteps[b-2],highestStep:this.xHighestCompleteStep[b-2]},thisStep:{startValue:this.xVal[b-1],step:this.xNumSteps[b-1],highestStep:this.xHighestCompleteStep[b-1]},stepAfter:{startValue:this.xVal[b-0],step:this.xNumSteps[b-0],highestStep:this.xHighestCompleteStep[b-0]}}};x.prototype.countStepDecimals=function(){var b=this.xNumSteps.map(L);return Math.max.apply(null,
b)};x.prototype.convert=function(b){return this.getStep(this.toStepping(b))};var V={to:function(b){return void 0!==b&&b.toFixed(2)},from:Number};return{version:m,create:function(b,a){if(!b||!b.nodeName)throw Error("noUiSlider ("+m+"): create requires a single element, got: "+b);if(b.noUiSlider)throw Error("noUiSlider ("+m+"): Slider was already initialized.");var c=qa(a,b);a=Ga(b,c,a);return b.noUiSlider=a,a}}});app.onReady(window,"$",function(){$(function(){function c(){var c=e.noUiSlider.get(),l=parseInt(c[0]);c=parseInt(c[1]);var g=location.search;g=l!==r||c!==C?updateURLVar(g,"filter_price",l+"-"+c):updateURLVar(g,"filter_price","");var q=$("<div class='popup f-in'><div class='loader popup-inner'></div></div>");$("body").append(q);var H=[],A=null;t.each(function(){var c=[],e=$(this);e.find(".filter input").each(function(e,l){l.checked&&c.push(l.value)});0<c.length&&("category"===e.attr("data-group-type")?
A=c.join(","):H.push(c.join(",")))});g=updateURLVar(updateURLVar(g,"page"),"filter",H.join("_"));g=updateURLVar(g,"filter_category",A);var x=location.pathname+g;!0===localStorage.reloadPage?location.href=x:$.ajax({url:x,success:function(c){try{c=$(c),history.pushState(null,"",x),$("#content .main-content").html(c.find("#content .main-content").html()),$("#content .bottom-bar").html(c.find("#content .bottom-bar").html()),q.remove(),addClearFix&&addClearFix()}catch(N){localStorage.reloadPage=!0,location.href=
x}}})}function q(c,l){var g=[null,null];g[c]=l;e.noUiSlider.set(g)}var e=$("#rang-slider"),g=[$("#range-to"),$("#range-from")],t=$(".filters .filter-group"),A=parseInt(e.attr("data-from")),L=parseInt(e.attr("data-to")),r=parseInt(e.attr("data-min")),C=parseInt(e.attr("data-max"));r=r===C?0:r;e=e.get(0);noUiSlider.create(e,{start:[A,L],connect:!0,range:{min:r,max:C}});e.noUiSlider.on("update",function(c,e){g[e].val(parseInt(c[e]).toCommaFormat())});e.noUiSlider.on("change",c);g.forEach(function(g,
l){g.on("change",function(){q(l,g.val().replaceAll(",",""))});g.on("keydown",function(g){var r=e.noUiSlider.get();r=Number(r[l]);var t=e.noUiSlider.steps()[l];switch(g.which){case 13:q(l,this.value.replaceAll(",",""));c();break;case 38:g=t[1];!1===g&&(g=1);null!==g&&q(l,r+g);break;case 40:g=t[0],!1===g&&(g=1),null!==g&&q(l,r-g)}})});decodeURIComponent(getURLVar("filter")).split("_").forEach(function(c){c.split(",").forEach(function(c){c=$(".filters input[name=filter][value='"+c+"']");c.size()&&(c.get(0).checked=
!0,c.parents(".filter-group").addClass("show"))})});decodeURIComponent(getURLVar("filter_category")).split("_").forEach(function(c){c.split(",").forEach(function(c){c=$(".filters input[name=category][value='"+c+"']");c.size()&&(c.get(0).checked=!0,c.parents(".filter-group").addClass("show"))})});t.each(function(){var e=$(this);e.find(".label").on("click",function(){e.toggleClass("show")});e.on("change",c)});window.onpopstate=function(c){location.reload(!0)}})},20);



