var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(b,e,c){b instanceof String&&(b=String(b));for(var a=b.length,d=0;d<a;d++){var f=b[d];if(e.call(c,f,d,b))return{i:d,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,e,c){b!=Array.prototype&&b!=Object.prototype&&(b[e]=c.value)};
$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(b,e,c,a){if(e){c=$jscomp.global;b=b.split(".");for(a=0;a<b.length-1;a++){var d=b[a];d in c||(c[d]={});c=c[d]}b=b[b.length-1];a=c[b];e=e(a);e!=a&&null!=e&&$jscomp.defineProperty(c,b,{configurable:!0,writable:!0,value:e})}};
$jscomp.polyfill("Array.prototype.find",function(b){return b?b:function(b,c){return $jscomp.findInternal(this,b,c).v}},"es6","es3");
app.onReady(window,"$",function(){function b(b,a,d){var f=this,c=this.body=$('<div class="popup f-in"><div class="popup-inner p-15 bg-white" style="min-width: 350px; text-align: left"><div class="popup-title"></div><div class="popup-body"></div><span class="popup-close" href="#"></span></div></div>');c.find(".popup-body").load(a,void 0,d);c.find(".popup-title").text(b);c.find(".popup-close").on("click",function(){f.close()});f.render()}var e=b.prototype;e.render=function(){$("body").append(this.body);
this.body.show()};e.close=function(){this.body.remove()};$(function(){function c(){f.body.find("form").on("submit",function(a){a.preventDefault();var d=$(this),b=d.find("button[type=submit]");$.ajax({url:"operator/product_update_request/add",method:"post",dataType:"json",data:new FormData(this),cache:!1,contentType:!1,processData:!1,beforeSend:function(){b.text("Submitting ..");b.attr("disabled","disabled")},complete:function(){b.text("Submit");b.removeAttr("disabled")},success:function(a){d.find(".text-danger").remove();
a.error&&d.prepend('<div class="text-danger">'+a.error+"</div>");a.success&&(f.close(),alert(a.success));a.reload&&location.reload()},error:function(a,d,b){alert(b+"\r\n"+a.statusText+"\r\n"+a.responseText)}})})}var a=$("input[name=product_id]").val(),d=$('<div class="row"><button type="button" data-loading-text="Loading..." class="btn btn-primary btn-lg btn-block">Update Price</button></div>');d.find("button");$.ajax({url:"operator/login/isLoggedIn",dataType:"json",success:function(a){1==a.is_logged_in&&
$(".cart-option").after(d)}});var f;d.on("click",function(){f=new b("Price Update Request","index.php?route=operator/product_update_request&product_id="+a,c)})})},20);app.onReady(window,"$",function(){$(function(){function b(a){var d=this;d.images=a;d.length=a.size();d.popup=new Popup('<div class="lb-body"></div><div class="lb-footer"><div class="title"></div><div class="counter"></div></div>');var b=d.popup.el.find(".popup-inner"),c=$('<span class="prev button"></span>'),e=$('<span class="next button"></span>');1<a.size()&&(b.before(c),b.after(e));c.on("click",function(){d.prev()});e.on("click",function(){d.next()});this.images.each(function(a,b){$(b).on("click",
function(b){b.preventDefault();d.show(a)})});d.index=0}var e=b.prototype;e.load=function(){var a=this.images.get(this.index),b=this.popup.el,c='<img title="'+a.title+'" alt="'+a.title+'" src="'+a.href+'"/>';b.find(".lb-body").html(c);b.find(".lb-footer .title").text(a.title);b.find(".lb-footer .counter").text(this.index+1+" of "+this.length)};e.show=function(a){this.index=a;this.load();this.popup.render()};e.prev=function(){this.index--;0>this.index&&(this.index=this.length-1);this.load()};e.next=
function(){this.index++;this.index>=this.length&&(this.index=0);this.load()};$("#button-cart").on("click",function(){$.ajax({url:"checkout/cart/add",method:"post",data:$("#input-enable-emi:checked, #product input[type='text'], #product input[type='hidden'], #product input[type='radio']:checked, #product input[type='checkbox']:checked, #product select, #product textarea"),dataType:"json",beforeSend:function(){$("#button-cart").button("loading")},complete:function(){$("#button-cart").button("reset")},
success:function(a){$(".alert, .text-danger").remove();$(".form-group").removeClass("has-error");var b=$(".container.alert-container");0==b.size()&&(b=$('<div class="container alert-container"></div>'),$(".after-header").after(b));if(a.error){if(a.error.option)for(i in a.error.option){var c=$("#input-option"+i.replace("_","-"));c.parent().hasClass("input-group")?c.parent().after('<div class="text-danger">'+a.error.option[i]+"</div>"):c.after('<div class="text-danger">'+a.error.option[i]+"</div>")}else"string"===
typeof a.error&&b.append('<div class="alert alert-danger"><i class="fa fa-exclamation-circle"></i> '+a.error+'<button type="button" class="close" data-dismiss="alert">&times;</button></div>');$(".text-danger").parent().addClass("has-error")}a.success&&(b.append('<div class="alert alert-success">'+a.success+'<button type="button" class="close" data-dismiss="alert">&times;</button></div>'),$(".cart-toggler .label").html(a.total),$(".cart-toggler .value").text(a.count),$("html,body").scrollTo(0,600),
cart.reload(),fbq("track","AddToCart",{content_ids:[product_id],content_type:"product",value:a.item_total,currency:"BDT"}))}})});$("#review, #question").delegate(".pagination a","click",function(a){a.preventDefault();a=$(this).parents("#review, #question");a.removeClass("f-in").addClass("f-out");a.load(this.href);a.removeClass("f-out").addClass("f-in")});$("#review").load("product/product/review?product_id="+product_id);$("#question").load("product/product/question?product_id="+product_id);$("#button-review, #button-question").on("click",
function(a){var b=$(this),c=b.parents("form");$.ajax({url:c.attr("action"),method:"post",dataType:"json",contentType:null,data:new FormData(c.get(0)),beforeSend:function(){b.button("loading")},complete:function(){b.button("reset")},success:function(a){$(".alert-success, .alert-danger").remove();a.error&&c.before('<div class="alert alert-danger"><i class="fa fa-exclamation-circle"></i> '+a.error+"</div>");a.success&&(c.before('<div class="alert alert-success"><i class="fa fa-check-circle"></i> '+a.success+
"</div>"),c.get(0).reset())}})});$(".share-ico").on("click",function(){shareOnSocialMedea($(this).data("type"),location.href,$(".product-title h1").text(),$(".main-img").attr("src"))});$(".view-more").on("click",function(a){a.preventDefault();a=$("#specification");0===a.length&&(a=$("#description"));$("html,body").scrollTo(a.offset().top-140,600)});$("[data-area]").on("click",function(a){a.preventDefault();a=$(this);$("html,body").scrollTo($("#"+a.data("area")).offset().top-140,600)});var c=$(".quantity [name=quantity]");
$(".quantity .ctl").on("click",function(){var a=$(this),b=+c.val();a.is(".increment")?b++:b--;isNaN(b)||1>b?c.val(1):c.val(b)});new b($(".product-images a"))})},20);


// console.log("Clicked")